### ISSUE TITLE
Do you faced this crash?

### ISSUE THREAD

**Issue by davidbilly** [cliqz-oss/browser-android#1]
Hi @cliqz-oss-ci , sorry for trouble you. Do you have faced this following crash? while using crosswalk as webview.

null exception when getNavigationHistory()?

Thanks!

Impacted Cases
------------------
1)  Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.xwalk.core.XWalkNavigationHistory.canGoForward()' on a null object reference
at CustomWebView.canGoForward(CustomWebView.java:398)

The CustomWebView was extends XWalkView class

2)  Caused by java.lang.NullPointerException at getNavigationHistory()

The CustomWebView was extends XWalkView class

3)  Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.xwalk.core.internal.XWalkNavigationHistoryInternal.size()' on a null object reference
at org.xwalk.core.internal.XWalkContentsClientBridge$1.handleMessage(XWalkContentsClientBridge.java:131)

Reproduce Test Steps
--------------------------

Just some certain phone will crash.

Devices list :
Samsung SM-J700F 
Samsung SM-G531H
Samsung GT-I9152
Sony D2533
Sony E5353
Sony SO-01G
Sony SOV31
HUAWEI TIT-AL00
Lenovo A7020a48
Samsung SM-G530BT
Samsung SM-G900F

Expected Outcome
----------------------

Wont crash

Actual Outcome
----------------------

App Crash.

Test Case Source Code
----------------------

1)  for (int i = 0; i < getNavigationHistory().size(); i++)
clearCacheForSingleFile(getNavigationHistory().getItemAt.getUrl());
// Clear the history
getNavigationHistory().clear();

2) getNavigationHistory().canGoForward()
getNavigationHistory().canGoBack()

3)  etNavigationHistory().navigate(XWalkNavigationHistory.Direction.FORWARD, steps);

Reference : https://crosswalk-project.org/jira/browse/XWALK-7474

**Comment by spacifici** [comment]
Nope, we do not use Crosswalk in that way so we never found this crash
